### ISSUE TITLE
Integrate tests for simple functions

### ISSUE THREAD

**Issue by nish-kishore** [nish-kishore/sirfunctions#51]
Integrate `test_that` features into package to incorporate continuous integration

**Comment by mcuadera** [comment]
I have encountered a problem with testing `f.metadata.tag()` using `testthat`. This test fails:
```  
raw.data <- list(metadata = list(download_time = "2022-01-01"))
expect_no_error(f.metadata.tag(ggplot_fig),
                           message = "raw.data was defined but generated an error")
```
I suspect that this is due to the default parameter in `f.metadata.tag()`:
```
time_tag = ifelse(exists("raw.data"), raw.data$metadata$download_time, NA)
```
If `raw.data` isn't already global, the test doesn't work. Instead, I would suggest an explicit assignment of `raw_data` rather than assuming `raw.data` is global. Another benefit is that the function is less dependent on global variables.  We change the function into something like:

`f.metadata.tag(ggplot.fig, raw_data = NA, time_tag = NA)`

This way, we can do a check in the function body like so:
```
  # use raw.data time_tag by default unless tag is explicitly stated
  if (!is.na(time_tag)) {

  } else if (!is.na(raw_data)) {
    time_tag = raw_data$metadata$download_time
  } else {
    stop("Please provide the raw.data file or a value for 'time_tag'")
  }
```
Users could then use the function as follows:
`f.metadata.tag(ggplot.object, time_tag = "2022-01-01")` or `f.metadata.tag(ggplot.object, raw_data = raw.data)`

We could also add in a check to make sure the object being passed in `raw_data` is actually the `raw.data` we want (simple check to see if `.$metadata$download_time` exists). 

Thoughts?
